# https://eslint.org/docs/user-guide/configuring
env:
  browser: true
  es2021: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
rules:
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0
  react/function-component-definition:
    [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  functional/functional-parameters: 0
  functional/immutable-data: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/no-return-void: 0
  functional/no-throw-statement: 0
  functional/no-try-statement: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  testing-library/no-debug: 0
ignorePatterns:
  [
    "node_modules/",
    "**/node_modules/",
    "/**/node_modules/*",
    "out/",
    "dist/",
    "build/",
  ]
